# Generated by Django 2.0.2 on 2018-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='coin_price',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coins',
            name='coin_volume',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coins',
            name='market_cap',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
